language: objective-c
podfile: Tests/Podfile
before_install:
  - gem install cocoapods
script:
  - xctool -project Tests/Tests.xcodeproj -scheme Tests -sdk iphonesimulator test
# - xctool -workspace Tests/Tests.xcworkspace -scheme Tests -sdk iphonesimulator build test
